name: Doxygen GitHub Pages Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        
      - name: Generate Doxygen Documentation
        run: doxygen
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/html
          branch: gh-pages
